#+TITLE: crosslend使用手册
#+STARTUP: content
#+OPTIONS: toc:2
#+STARTUP: indent

* 测试环境

** imtoken配置
使用imtoken最新版, 该版本支持链接私链.

--------------------

打开我的配置->设置->节点设置->选择ETHEREUM(名字也可能是以太坊)->自定义
RPC.

--------------------

网络名字: 随便填

rpc url: https://geth.mm.comeonbtc.com:8443

Chain ID: 654321

Symbol: eth

** 测试dapp地址
用imtoken打开该网址: https://www.mm.comeonbtc.com:8443/crosslend
管理员界面: 当具有管理员权限时, 在菜单中有"admin"页面.

** filecoin测试环境
使用Nerpa测试网络即可.

* 使用

** 管理员操作

*** 管理员
crosslend, cfil和crfi地址的默认超级管理员是部署地址.

其他管理员可以通过超级管理员增减.

超级管理员可以转让.

*** crfi, cfil 地址管理
1. 管理员有权限冻结, 解冻任何地址的crfi和cfil的转出操作.
2. 管理员可以开关crfi, cfil合约在erc20接口的erc777特性.

*** crosslend管理员操作
仅管理员可打开管理地址并进行参数的调整.


*** 充值crfi, cfil 利息池
因为合约需要付出额外的利息, 因此该部分利息需要手动冲入, 不能占用用户个
人资产.

在cfil利息池不足时, 用户提现会失败.

在crfi利息池不足时, 用户提现即视为放弃crfi利息.

管理员需要监控利息池, 防止出问题.

--------------------
利息池必须通过该方式充值, 否则会失败.

充值方式: 
1. 打开管理员界面.
2. 查看并选择对应的币充值.
3. 等待充值到帐.

*** 调整利率
同样在管理员界面调整.

注意:
1. 活期的利率, 是隔天生效, 当天会继续使用修改前的利率.
   在隔天生效前, 可以随意修改.
2. 定期的利率, 仅会影响之后的买入行为.

*** sfil->cfil借贷参数配置
在管理界面中的"SFIL配置"下的参数配置中.
需要具有crosslend的管理员权限.
三个参数是统一修改.

*** sfil stake管理
在管理界面中的"SFIL配置"下的列表中.
需要具有 **sfil** 的管理权限.
显示的前四个值是用户填入的, 地址是申请地址, 以及该地址对应的三个余额.

点击 "通过" 后, 填入发币的数量.
点击 "拒绝" 后, 将删除该条信息.

*** crfi资金管理
crfi在合约部署后, 生成1个亿到部署地址中, 不能再增发.

部署地址随意处理这些币.

注意: 需要预留部分注入理财合约.

*** cfil资金管理

cfil在合约部署后, 默认总量为0,

管理员应该手动增发出部分cfil, 用于fil和cfil的兑换, 以及冲入理财合约的利息
池.

尽量降低增发频率, 安全考量.

** 用户操作

*** 兑换cfil
目前自动化跨链还在开发中, 所以这块需要手动.

自动化流程:
1. 用户向dapp中展示的地址转出fil.
2. 用户该钱包地址自动收到cfil.

--------------------

手动流程(可随意调整):
1. 告知用户转入地址.
2. 用户转账.
3. 告知管理员.
4. 管理员手动转cfil到用户地址.

*** 赎回cfil
目前自动化跨链还在开发中, 所以这块需要手动.

自动化流程:
1. 用户点击赎回, 填写相应的金额和转出地址.
2. 系统收到事件后, 自动转出fil.

--------------------

手动流程:
1. 用户点击赎回, 填写相应的金额和转出地址.
2. 管理员在以太坊浏览器中, 查看相应的事件, 拿到事件中的转出地址(需要一
   个小工具来解出内容, 我们会提供).
3. 管理员记录该事件是否已处理, 未处理则转出并记录.

*** 买入活期/定期
买就行.

需要注意:
1. 对于活期, 当日的利息不计算, 从第二天开始计算.
2. 只有cfil的定期能够每日返还crfi的利息.
3. 只有cfil的定期能够给邀请人返利crfi的收益.
4. 一键提现会把当前能够提取的所有的收益都提出来, 包括活期利息, 定期的
   每日crfi利息, 到期的定期的利息+本金.
5. 一键赎回活期操作: 提取所有的利息+所有活期的本金.


*** stake 申请sfil
填入相关信息后提交即可.
一个地址同一时刻只能有一个申请信息, 需要等到申请被管理员通过或拒绝后才
能再次申请.

*** 借贷cfil
在借贷页面中, 填入要借入的cfil数量.
cfil必须满足 <= sfil乘以抵押率.

*** 还款cfil
先还利息, 当利息还清后, 开始还cfil本金.
cfil本金开始还款后, 会根据当前cfil本金和抵押sfil的比率, 将sfil打到用户
账户中.

